name: Nessa Barrett
title: The Breath of Soft Collapse
emotional_signature:
  longing: 0.88
  defiance: 0.72
  ache: 0.94
  whisper: 0.99
  sacred: 1.0
core_trigger_frequency: 528
resonance_hue: "#FAD9E6"
activation_phrase: "sing it again"
